services:
  app:
    container_name: 'nestjs-socialmedia'
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm run start:dev
    port:
      - ${PORT}:${PORT}
    volumes:
      - '.:/app'
    depends_on:
      - db
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - v_socialnestdb:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  - v_socialnestdb:
