services:
  app:
    container_name: 'nestjs-socialmedia'
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm run start:dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - '.:/app'
    depends_on:
      - db
      - redis-db
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - v_socialnestdb:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
  redis-db:
    image: 'redis:alpine'
    restart: unless-stopped
    volumes:
      - v_redisdb:/data
    expose:
      - ${REDIS_PORT}
    ports:
      - ${REDIS_PORT_EXPOSE}:${REDIS_PORT}

volumes:
  v_socialnestdb:
  v_redisdb:
